#!/bin/bash

### Catppuccin
export RED=0xfffb4934
export YELLOW=0xfffabd2f
export ORANGE=0xfffab387
export GREEN=0xffb8bb26
export GREEN_BG=0x19b8bb26
export LAVENDER=0xffebdbb2
export LAVENDER_BG=0x19ebdbb2
export FLAMINGO=0xfffabd2f
export FLAMINGO_BG=0x19fabd2f
export PINK=0xfffb4934
export PINK_BG=0x19fb4934

export OVERLAY1=0xff928374

# General bar colors
export BAR_COLOR=0x00000000
export LABEL_COLOR=$OVERLAY1

export POPUP_BACKGROUND_COLOR=0xFF272936

# Item colors
export SPACE_SELECTED=$LAVENDER
export SPACE_SELECTED_BACKGROUND=$LAVENDER_BG
export SPACE=$OVERLAY1
export SPACE_BACKGROUND=0x00000000

export CALENDAR=$LAVENDER
export CALENDAR_BACKGROUND=$LAVENDER_BG

export BATTERY=$GREEN
export BATTERY_WARNING=$YELLOW
export BATTERY_CRITICAL=$RED
export BATTERY_BACKGROUND=$GREEN_BG

export WIFI=$FLAMINGO
export WIFI_BACKGROUND=$FLAMINGO_BG

export VOLUME=$PINK
export VOLUME_BACKGROUND=$PINK_BG
