#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="Maple Mono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# aerospace setting
AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

# Setting up the general bar appearance of the bar
bar=(
  height=30
  notch_display_height=42
  notch_offset=-7
  color=$BAR_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=2
  padding_left=2
  margin=10
  corner_radius=8
  topmost=window
  blur_radius=0
  y_offset=7
)

sketchybar --bar "${bar[@]}"

# Setting up default item properties
defaults=(
  updates=when_shown

  # icon
  icon.drawing=off
  icon.padding_left=0
  icon.padding_right=0
  icon.font="$FONT:Regular:14.0"

  # label/text
  label.font="$FONT:Regular:14.0"
  label.color=$LABEL_COLOR

  # padding
  label.padding_left=8
  label.padding_right=8
  padding_right=2
  padding_left=2

  # background
  background.height=24
  background.corner_radius=5
  background.border_width=2

  # popup
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on

  scroll_texts=on
)

sketchybar --default "${defaults[@]}"


# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
