#!/usr/bin/env bash

main() {
    # sanity check
    if [[ "$1" = "" ]]; then
        printf "Invalid argument count! Missing platform (linux-desktop, macbook)\n"

	exit 1
    fi

    # create the .config directory if it does not exists
    mkdir -p $HOME/.config

    # link the home-manager directory of not linked
    ln -s $(pwd) $HOME/.config || true

    # build the home-manager config
    nix-shell -p nixUnstable --command "nix build --experimental-features 'nix-command flakes' '.#$1'"
}

set -eo pipefail

main "$@"
